// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolBook.Data;

namespace SchoolBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200916161927_EvaluationObservationsFix4")]
    partial class EvaluationObservationsFix4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "f67df2ce-0448-42a9-be11-3c68ea78d9c1",
                            ConcurrencyStamp = "48d62dea-f3da-4a93-b29a-238f32b8110b",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "295b11cf-22e3-48b3-b6ab-538653c98c04",
                            ConcurrencyStamp = "5699460f-69a0-44b4-a503-bf7d71455516",
                            Name = "Profesor",
                            NormalizedName = "PROFESOR"
                        },
                        new
                        {
                            Id = "8176f8e0-49bf-44bd-9655-d39b9cf7111d",
                            ConcurrencyStamp = "e83e495d-60b3-4f97-96b5-421ddfde7307",
                            Name = "Apoderado",
                            NormalizedName = "APODERADO"
                        },
                        new
                        {
                            Id = "05ea2c83-210a-446d-971b-ecdf4f489461",
                            ConcurrencyStamp = "54461591-525d-4d79-b307-0e20e792ee4f",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SchoolBook.Models.Bulletin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bulletins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Esto es demasiado interesante..",
                            Image = "https://www.elosceolastar.com/wp-content/uploads/2020/07/empty-classroom_elementary-school-middle-school-high-school.jpg",
                            Subtitle = "Que tema tan interesante nos hablan hoy",
                            Title = "Noticia de prueba 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Esto es demasiado interesante..",
                            Image = "https://www.andree.cl/home3/images/stories/slideshow2014/foto_03.jpg",
                            Subtitle = "Que tema tan interesante nos hablan hoy",
                            Title = "Noticia de prueba 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Esto es demasiado interesante..",
                            Image = "https://lh5.googleusercontent.com/proxy/dv9-TY9gKRTLd9zTuxrQYfx6H67fgMhCBBBjHNDZrSdv0RDqhiI3a8SBmQyHXyVVz983bM53TmXyiSU",
                            Subtitle = "Que tema tan interesante nos hablan hoy",
                            Title = "Noticia de prueba 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Esto es demasiado interesante..",
                            Image = "https://www.sketchup.com/sites/www.sketchup.com/files/molecule_image/IMG_01_SCHOOL_SCENE_01_low-1.png",
                            Subtitle = "Que tema tan interesante nos hablan hoy",
                            Title = "Noticia de prueba 4"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "7A",
                            Description = "A",
                            GradeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "7B",
                            Description = "B",
                            GradeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "8A",
                            Description = "A",
                            GradeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "8A",
                            Description = "B",
                            GradeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "1A",
                            Description = "A",
                            GradeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "1B",
                            Description = "B",
                            GradeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "2A",
                            Description = "A",
                            GradeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "2B",
                            Description = "B",
                            GradeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "3A",
                            Description = "A",
                            GradeId = 5
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "3B",
                            Description = "B",
                            GradeId = 5
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "4A",
                            Description = "A",
                            GradeId = 6
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "4B",
                            Description = "B",
                            GradeId = 6
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.ClassSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 2,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 3,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 4,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 5,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 6,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 6,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 6,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 7,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 7,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 7,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 7,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 8,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 8,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 8,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 8,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 49,
                            ClassId = 9,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 50,
                            ClassId = 9,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 51,
                            ClassId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 52,
                            ClassId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 53,
                            ClassId = 9,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 54,
                            ClassId = 9,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 55,
                            ClassId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 56,
                            ClassId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 57,
                            ClassId = 10,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 58,
                            ClassId = 10,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 59,
                            ClassId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 60,
                            ClassId = 10,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 61,
                            ClassId = 11,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 62,
                            ClassId = 11,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 63,
                            ClassId = 11,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 64,
                            ClassId = 11,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 65,
                            ClassId = 11,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 66,
                            ClassId = 11,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 67,
                            ClassId = 12,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 68,
                            ClassId = 12,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 69,
                            ClassId = 12,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 70,
                            ClassId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 71,
                            ClassId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 72,
                            ClassId = 12,
                            SubjectId = 6
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enseñansa Básica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enseñansa Media"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.EducationGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.HasIndex("GradeId");

                    b.ToTable("EducationGrades");
                });

            modelBuilder.Entity("SchoolBook.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(2,1)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Evaluations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Historia de Chile 1",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Historia de Chile 2",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Trabajo Presidentes de Chile",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Historia Mundial",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Historia Universal",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            ClassSubjectId = 1,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Cultura Chopistica",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            ClassSubjectId = 2,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Ecuaciones Diferenciales",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            ClassSubjectId = 2,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Geometria",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            ClassSubjectId = 2,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Trabajo Aritmetica",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            Active = false,
                            ClassSubjectId = 2,
                            Coefficient = 0m,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            PeriodId = 1,
                            Title = "Prueba Planos Cartesianos",
                            TypeId = 5
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.EvaluationObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObserverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ObserverId");

                    b.HasIndex("StudentId");

                    b.ToTable("Observations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "No quiso entregar la prueba.",
                            EvaluationId = 10,
                            LastModification = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObserverId = "868465e8-48d1-4b1e-96e0-87bfca64f213",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "No entrega trabajo a la fecha..",
                            EvaluationId = 10,
                            LastModification = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ObserverId = "868465e8-48d1-4b1e-96e0-87bfca64f213",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.EvaluationScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EvaluationId = 1,
                            Score = 2.1m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            EvaluationId = 2,
                            Score = 4.4m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            EvaluationId = 3,
                            Score = 3.9m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            EvaluationId = 4,
                            Score = 4.4m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 5,
                            EvaluationId = 5,
                            Score = 1.9m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 6,
                            EvaluationId = 6,
                            Score = 5.6m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            EvaluationId = 1,
                            Score = 4.4m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 8,
                            EvaluationId = 2,
                            Score = 2.5m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 9,
                            EvaluationId = 3,
                            Score = 1.5m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 10,
                            EvaluationId = 4,
                            Score = 3.5m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 11,
                            EvaluationId = 5,
                            Score = 1.5m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 12,
                            EvaluationId = 6,
                            Score = 3.1m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 13,
                            EvaluationId = 1,
                            Score = 4.6m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 14,
                            EvaluationId = 2,
                            Score = 5.8m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 15,
                            EvaluationId = 3,
                            Score = 5.6m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 16,
                            EvaluationId = 4,
                            Score = 4.5m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 17,
                            EvaluationId = 5,
                            Score = 1.3m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 18,
                            EvaluationId = 6,
                            Score = 4.5m,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 19,
                            EvaluationId = 1,
                            Score = 3.4m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 20,
                            EvaluationId = 2,
                            Score = 7.0m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 21,
                            EvaluationId = 3,
                            Score = 4.4m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 22,
                            EvaluationId = 4,
                            Score = 5.2m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 23,
                            EvaluationId = 5,
                            Score = 1.2m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 24,
                            EvaluationId = 6,
                            Score = 4.0m,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 25,
                            EvaluationId = 1,
                            Score = 5.6m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 26,
                            EvaluationId = 2,
                            Score = 6.0m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 27,
                            EvaluationId = 3,
                            Score = 1.7m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 28,
                            EvaluationId = 4,
                            Score = 5.8m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 29,
                            EvaluationId = 5,
                            Score = 7.0m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 30,
                            EvaluationId = 6,
                            Score = 5.8m,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 31,
                            EvaluationId = 1,
                            Score = 1.7m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 32,
                            EvaluationId = 2,
                            Score = 5.4m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 33,
                            EvaluationId = 3,
                            Score = 5.7m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 34,
                            EvaluationId = 4,
                            Score = 6.5m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 35,
                            EvaluationId = 5,
                            Score = 5.2m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 36,
                            EvaluationId = 6,
                            Score = 1.5m,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 37,
                            EvaluationId = 1,
                            Score = 2.4m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 38,
                            EvaluationId = 2,
                            Score = 3.0m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 39,
                            EvaluationId = 3,
                            Score = 6.9m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 40,
                            EvaluationId = 4,
                            Score = 3.6m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 41,
                            EvaluationId = 5,
                            Score = 4.6m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 42,
                            EvaluationId = 6,
                            Score = 1.5m,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 43,
                            EvaluationId = 1,
                            Score = 5.8m,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 44,
                            EvaluationId = 2,
                            Score = 4.5m,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 45,
                            EvaluationId = 3,
                            Score = 1.6m,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 46,
                            EvaluationId = 4,
                            Score = 3.3m,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 47,
                            EvaluationId = 5,
                            Score = 5.6m,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 48,
                            EvaluationId = 6,
                            Score = 6.6m,
                            StudentId = 8
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.EvaluationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvaluationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nota parcial"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Examen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Promedio Período"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Promedio Final"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Prueba Acumulativa"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Prueba de Nivel"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Septimo Básico",
                            YearId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Octavo Básico",
                            YearId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Primero Medio",
                            YearId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Segundo Medio",
                            YearId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tercero Medio",
                            YearId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cuarto Medio",
                            YearId = 1
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Msg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SchoolBook.Models.MenuOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupMenuOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Libro de Clases",
                            GroupMenuOptionId = 0,
                            Icon = "small-icon svgcollege-029-papyrus",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Notas",
                            GroupMenuOptionId = 1,
                            Order = 1,
                            Url = "/ClassBook"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Anotaciones",
                            GroupMenuOptionId = 1,
                            Order = 4,
                            Url = "Observations"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Evaluaciones",
                            GroupMenuOptionId = 1,
                            Order = 2,
                            Url = "/ClassBook/Evaluations"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Observaciones",
                            GroupMenuOptionId = 1,
                            Order = 3,
                            Url = "/ClassBook/Observations"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Asistencia",
                            GroupMenuOptionId = 1,
                            Order = 5,
                            Url = "Attendance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Atrasos",
                            GroupMenuOptionId = 1,
                            Order = 6,
                            Url = "Delays"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Alumnos",
                            GroupMenuOptionId = 0,
                            Icon = "small-icon svgcollege-019-reading-book",
                            Order = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ficha Alumno",
                            GroupMenuOptionId = 8,
                            Order = 1,
                            Url = "Student"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Accidente Escolar",
                            GroupMenuOptionId = 8,
                            Order = 2,
                            Url = "Accidents"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Administración",
                            GroupMenuOptionId = 0,
                            Icon = "small-icon svgcollege-043-test",
                            Order = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Credenciales",
                            GroupMenuOptionId = 11,
                            Order = 1,
                            Url = "Credentials"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Cambiar Contraseña",
                            GroupMenuOptionId = 11,
                            Order = 2,
                            Url = "Password"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Horarios",
                            GroupMenuOptionId = 0,
                            Icon = "small-icon svgcollege-005-alarm",
                            Order = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Crear Horarios",
                            GroupMenuOptionId = 14,
                            Order = 1,
                            Url = "ScheduleMaker"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Horario Por Asignatura",
                            GroupMenuOptionId = 14,
                            Order = 2,
                            Url = "ScheduleMaker?type=1"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Horario Por Curso",
                            GroupMenuOptionId = 14,
                            Order = 3,
                            Url = "ScheduleMaker?type=2"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Horario Por Profesor",
                            GroupMenuOptionId = 14,
                            Order = 4,
                            Url = "ScheduleMaker?type=3"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypePeriodId")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypePeriodId");

                    b.HasIndex("YearId");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Primer Semestre",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypePeriodId = 1,
                            YearId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segundo Semestre",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypePeriodId = 1,
                            YearId = 1
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuOptionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MenuOptionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("SchoolBook.Models.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("SchoolYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2020
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Juanito Perez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Luchito Jara"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kenita Larrain"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luly Love"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Felipito Camiroa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Don Francisquito"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Julito Videla"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Arturito Vidal"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.StudentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentsClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 5,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 4,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 5,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 6,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 4,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 6,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 4,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 5,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 6,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 2,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 4,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 6,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 2,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 4,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 5,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 6,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 2,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 3,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 4,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 5,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 6,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 2,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 3,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 4,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 5,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 6,
                            StudentId = 8
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Historia y Geografía",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Matemáticas",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lenguaje y Comunicaciones",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Biología",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Química",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Física",
                            Order = 6
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.TypePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypePeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Semestral"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trimestral"
                        });
                });

            modelBuilder.Entity("SchoolBook.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("IdSuperior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SchoolBook.Models.UserSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSelections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SchoolBook.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SchoolBook.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SchoolBook.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.Class", b =>
                {
                    b.HasOne("SchoolBook.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.ClassSubject", b =>
                {
                    b.HasOne("SchoolBook.Models.Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.EducationGrade", b =>
                {
                    b.HasOne("SchoolBook.Models.Education", "Education")
                        .WithMany("EducationGrades")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.Grade", "Grade")
                        .WithMany("EducationGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.Evaluation", b =>
                {
                    b.HasOne("SchoolBook.Models.ClassSubject", "ClassSubject")
                        .WithMany("Evaluations")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.TypePeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.EvaluationType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.EvaluationObservation", b =>
                {
                    b.HasOne("SchoolBook.Models.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.User", "Observer")
                        .WithMany()
                        .HasForeignKey("ObserverId");

                    b.HasOne("SchoolBook.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.EvaluationScore", b =>
                {
                    b.HasOne("SchoolBook.Models.Evaluation", "Evaluation")
                        .WithMany("Scores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.Grade", b =>
                {
                    b.HasOne("SchoolBook.Models.SchoolYear", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.Period", b =>
                {
                    b.HasOne("SchoolBook.Models.TypePeriod", "TypePeriod")
                        .WithMany()
                        .HasForeignKey("TypePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.SchoolYear", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.RoleMenu", b =>
                {
                    b.HasOne("SchoolBook.Models.MenuOption", "MenuOption")
                        .WithMany()
                        .HasForeignKey("MenuOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("SchoolBook.Models.StudentClass", b =>
                {
                    b.HasOne("SchoolBook.Models.Class", "Class")
                        .WithMany("StudentClass")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolBook.Models.Student", "Student")
                        .WithMany("StudentClass")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolBook.Models.UserSelection", b =>
                {
                    b.HasOne("SchoolBook.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
